### ISSUE TITLE
Multiple `~` temp files in repo and missing `obj` dir

### ISSUE THREAD

**Issue by dsclassen** [rcsb/RNAView#5]
There are numerous files in `src` with a `~` at the end. I assume this was accidentally committed as these are likely the result of using `gedit` or `vim` or something to edit the files?

Also in order to get the code to compile I needed to manually create the `obj` directory.

**Comment by mmagnus** [comment]
```
(base) ➜  RNAView git:(master) make
cc -g -Wall -I./include  -c ./src/rnaview.c -o obj/rnaview.o
error: unable to open output file 'obj/rnaview.o': 'No such file or directory'
1 error generated.
make: *** [obj/rnaview.o] Error 1
```

OK, so manual creation of the folder solves my problem, thanks!

**Comment by mmagnus** [comment]
works! thanks!
